### PR TITLE
Implement Skip support

### PR DESCRIPTION
**Pull request by marcprux**
This PR adds support for Skip so the library can run on Android. Since Skip doesn't support executable targets, I've implemented a test case that just outputs a random cow to the console.

### CODE REVIEW

**Comment by helje5** [comment]
Is a test target required?

**Comment by marcprux** [comment]
Test targets aren't required, but since Skip doesn't support `.executable` products, that's the only way to run the code to try it out (short of making a whole Android app and embedding the framework).

**Comment by helje5** [comment]
Ouch, we got infected for no reason 🙈 
```
// This is free software: you can redistribute and/or modify it
// under the terms of the GNU Lesser General Public License 3.0
```

**Comment by marcprux** [comment]
> Ouch, we got infected for no reason 🙈
> 
> ```
> // This is free software: you can redistribute and/or modify it
> // under the terms of the GNU Lesser General Public License 3.0
> ```

Heh. Feel free to remove … that was just copied over from another project.

**Pull request merged**
